version: "3.8"

services:
  backend:
    image: rajbhut/oncomp
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
